log:
  level: debug

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: password
  db_name: auth
  max_idle_conns: 10
  max_open_conns: 100

redis:
  type: cluster
  addrs: :7001,:7002,:7003,:7004,:7005,:7006
  password: password
  db: 0
  pool_size: 40
  pool_timeout: 3
  read_only: false
  max_retries: 5

jaeger:
  endpoint: localhost:4317

jwt:
  secret: password
  access_token_expires: 10800
  refresh_token_expires: 86400
