global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'account_monitor'
    static_configs:
    - targets: ['host.docker.internal:9001']

  - job_name: 'purchase_monitor'
    static_configs:
    - targets: ['host.docker.internal:9002']

  - job_name: 'product_monitor'
    static_configs:
    - targets: ['host.docker.internal:9003']

  - job_name: 'order_monitor'
    static_configs:
    - targets: ['host.docker.internal:9004']

  - job_name: 'payment_monitor'
    static_configs:
    - targets: ['host.docker.internal:9005']

  - job_name: 'orchestrator_monitor'
    static_configs:
    - targets: ['host.docker.internal:8080']